const en = {
  // Common
  common: {
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    back: "Back",
    loading: "Loading...",
    confirm: "Confirm",
    yes: "Yes",
    no: "No",
    enabled: "Enabled",
    disabled: "Disabled",
    configured: "Configured",
    not_configured: "Not Configured",
    coming_soon: "Coming Soon",
    available: "Available",
    click_to_manage: "Click to manage",
    click_to_setup: "Click to setup",
    click_to_customize: "Click to customize",
    required: "Required",
    optional: "Optional",
    search: "Search",
    no_results: "No results found",
    error: "Something went wrong",
    success: "Success",
  },

  // Navigation / Sidebar
  nav: {
    dashboard: "Dashboard",
    queue: "Queue",
    tickets: "Tickets",
    applications: "Applications",
    settings: "Settings",
    logout: "Logout",
    customer_dashboard: "Customer Dashboard",
    view_queue_panel: "View Queue Panel",
    view_queue_panel_hint: "Preview the queue panel to check how settings affect applications, tickets, and the queue view.",
  },

  // Auth
  auth: {
    login: "Login with Discord",
    logout: "Logout",
    login_description: "Sign in with your Discord account to continue",
  },

  // API errors
  errors: {
    unauthorized: "User not authenticated",
    forbidden: "Forbidden",
    insufficient_permissions: "You do not have permission to perform this action",
    bad_request: "Invalid request",
    invalid_request: "Invalid request",
    invalid_request_body: "Invalid request body",
    internal_error: "Internal server error",
    not_found: "Resource not found",
    conflict: "This action conflicts with the current state",
    owner_required: "Only the customer can update this setting",
    language_update_failed: "Failed to save language settings",
    language_retrieval_failed: "Failed to load language settings",
    queue_disabled: "Queue module is currently disabled",
    queue_locked: "Queue is currently locked",
    queue_staff_only_locked: "Queue is currently staff only",
    discord_config_required: "Configure Discord integration first",
    customer_session_required: "Customer session required to switch panels.",
    customer_session_check_failed: "Unable to verify your customer session.",
    steam_required: "Steam account linking is required before joining this queue",
    steam_banned: "This Steam account is banned from joining this queue",
    discord_banned: "This Discord account is banned from joining this queue",
    steam_recently_changed: "Your Steam account was changed recently and must cool down before joining this queue",
    steam_unlink_disabled: "Steam unlinking is disabled for this server",
  },

  // Steam identity
  steam_identity: {
    title: "Steam Identity",
    description: "Link Steam to help servers verify queue access and discourage alternate-account ban bypasses.",
    linked: "Steam linked",
    not_linked: "No Steam account linked",
    link: "Link Steam",
    unlink: "Unlink Steam",
    recently_changed: "Recently Changed",
    change_history: "Steam Change History",
    required_title: "Steam account required",
    required_description: "This server requires a linked Steam account before joining the queue.",
  },

  // txAdmin bans
  txadmin_bans: {
    title: "txAdmin Ban Sync",
    description: "Pull Steam and Discord ban identifiers from txAdmin playersDB.json, refresh during queue joins, and accept live ban/unban pushes from txAdmin events.",
    sync_now: "Sync Now",
    sync_success: "Ban sync complete",
    sync_failed: "Failed to sync bans from the server resource",
    active_bans: "Active Ban Identifiers",
    last_manual_sync: "Last Manual Sync",
    last_server_push: "Last Server Push",
    never: "Never",
    resource_config: "Server Resource Sync Configuration",
  },

  // Customer dashboard
  customer: {
    welcome: "Welcome back, {name}!",
    subtitle: "Manage your FiveM server configuration and queue settings.",
    setup_progress: "Setup Progress",
    required_completed: "{completed} of {total} required items completed",
    completed: "Completed",
    remaining: "Remaining",
    all_completed: "All required items completed!",
    done: "Done",

    // Section headers
    essential_setup: "Essential Setup",
    discord_configuration: "Discord Configuration",
    features: "Features",
    branding: "Branding",

    // Essential setup cards
    fivem_title: "FiveM API Configuration",
    fivem_desc_done: "Your FiveM server is configured and ready for queue management.",
    fivem_desc_pending: "Configure your FiveM API settings to enable queue management.",

    discord_title: "Discord Setup",
    discord_desc_done: "Your Discord bot is configured and ready for queue management.",
    discord_desc_pending: "Configure your Discord bot token and guild ID for queue management.",

    tebex_title: "Tebex API Configuration",
    tebex_desc_done: "Your Tebex API is configured and ready for payment tracking.",
    tebex_desc_pending: "Configure your Tebex API key to enable purchase history tracking.",

    // Discord configuration cards
    dashboard_roles_title: "Dashboard Roles Setup",
    dashboard_roles_desc: "Configure which Discord roles can access the dashboard and join the queue.",
    dashboard_roles_locked: "Complete Discord setup first to configure dashboard and queue access roles.",

    queue_roles_title: "Queue Builder",
    queue_roles_desc: "Configure priority roles, bypass slots, access rules, and native card behavior.",
    queue_roles_desc_done: "Your queue roles and access flow are configured.",
    queue_roles_locked: "Complete Discord setup first to configure queue rules and access.",

    moderators_title: "Moderators",
    moderators_desc: "Add moderators to help manage tickets and applications for your server.",
    moderators_desc_done: "You have moderators with access to tickets and applications.",
    moderators_locked: "Complete Discord setup first to manage moderators.",
    discord_required: "Complete Discord setup first",

    // Features cards
    module_settings_title: "Module Settings",
    module_settings_desc: "Enable or disable application, ticket, notification, and staff-facing modules.",

    application_builder_title: "Application Builder",
    application_builder_desc: "Create and manage form applications with custom questions for players to fill out.",

    tickets_title: "Tickets",
    tickets_desc: "Manage ticket categories and customize your support system for players and moderators.",

    notifications_title: "Discord Notifications",
    notifications_desc: "Configure Discord notifications for queue, applications, and tickets",

    queue_builder_title: "Queue Builder",
    queue_builder_desc: "Build and customize your queue system with advanced rules, priorities, and automation features.",

    language_title: "Language",
    language_desc: "Set the language for the player-facing interface.",

    // Branding cards
    app_customization_title: "App Customization",
    app_customization_desc: "Customize app-wide settings like primary color that apply to the entire application.",

    dashboard_customization_title: "Dashboard Customization",
    dashboard_customization_desc: "Customize your dashboard navbar logo that will be visible to you and all players/moderators.",

    home_page_title: "Home Page Customization",
    home_page_desc: "Customize your landing page appearance, content, and quick links for players.",

    login_customization_title: "Login Customization",
    login_customization_desc: "Customize your login page appearance, branding, and authentication flow.",

    custom_domain_title: "Custom Domain",
    custom_domain_desc_done: "Your custom domain is configured and ready to use.",
    custom_domain_desc_pending: "Configure a custom domain to use your own domain name for your landing page.",
  },

  // Language settings page
  language: {
    title: "Language",
    description: "Set the language for the player-facing interface.",
    select_label: "Interface Language",
    select_description: "This controls the language players see when using your queue, tickets, and applications.",
    select_language: "Select Language",
    select_language_description: "Choose the language players will see when using your queue, tickets, and applications.",
    customize_title: "Translation Overrides",
    customize_description: "Edit the translation payload used by your setup. Keep keys and placeholders intact.",
    download: "Download Translation File",
    reset: "Reset to Defaults",
    save_success: "Language saved successfully",
    save_error: "Failed to save language",
    invalid_json: "Translations must be valid JSON",
    mode_label: "Language Source",
    mode_preset: "Preset",
    mode_custom: "Custom",
    preset_description: "Use one of the bundled translation files maintained by the public language repository.",
    custom_description: "Use the customer-specific translation JSON below for this setup.",
    english: "English",
    spanish: "Spanish",
    norwegian: "Norwegian",
  },

  // Queue
  queue: {
    title: "Queue",
    position: "Position",
    join: "Join Queue",
    leave: "Leave Queue",
    players_in_queue: "{count} players in queue",
    your_position: "Your position: {position}",
    estimated_wait: "Estimated wait: {time}",
    queue_closed: "Queue is closed",
    queue_open: "Queue is open",
  },

  // Tickets
  tickets: {
    title: "Tickets",
    create: "Create Ticket",
    open: "Open",
    closed: "Closed",
    no_tickets: "No tickets yet",
    subject: "Subject",
    description: "Description",
    status: "Status",
    created_at: "Created",
    updated_at: "Last updated",
    close_ticket: "Close Ticket",
    ticket_closed: "Ticket closed",
    message_placeholder: "Type your message...",
    send: "Send",
    create_modal_title: "Create New Ticket",
    create_success: "Ticket created successfully!",
    create_error: "Failed to create ticket. Please try again.",
    related_title: "Related Tickets",
    related_count: "{count} linked ticket{plural}",
    related_search_label: "Search by Ticket ID",
    related_link: "Link",
    related_linked: "Related ticket linked",
    related_link_failed: "Failed to link related ticket",
    related_removed: "Related ticket removed",
    related_remove_failed: "Failed to remove related ticket",
    related_loading: "Loading ticket...",
    related_none_found: "No linkable ticket found for that ID.",
    related_none_linked: "No related tickets linked.",
    related_remove: "Remove",
    watcher_started: "Watching ticket",
    watcher_stopped: "Stopped watching ticket",
    watcher_dm_description: "Receive a DM when someone replies to this ticket.",
  },

  // Applications
  applications: {
    title: "Applications",
    submit: "Submit Application",
    no_applications: "No applications available",
    submitted: "Application submitted successfully",
    already_submitted: "You have already submitted this application",
    status: "Status",
    pending: "Pending",
    approved: "Approved",
    rejected: "Rejected",
    rejected_success: "Application rejected",
    cosigned_success: "Application co-signed",
    no_internal_notes: "No internal notes yet.",
  },

  // Discord notifications
  discord_notifications: {
    field_ticket_id: "Ticket ID",
    field_priority: "Priority",
    field_status: "Status",
    field_created_by: "Created By",
    field_opened_for: "Opened For",
    field_category: "Category",
    field_description: "Description",
    field_from: "From",
    field_reply: "Reply",
    field_ticket: "Ticket",
    field_user: "User",
    field_reason: "Reason",
    field_created: "Created",
    field_assigned_to: "Assigned To",
    field_escalated_by: "Escalated By",
    field_invited_by: "Invited by",
    field_queue_block: "Queue Block",
    button_rate_experience: "Rate your experience",
    auto_closed_footer: "If you still need help, please open a new ticket.",
    closed_status: "Closed",
    yes: "Yes",
    no: "No",
    queue_joined_dm_description: "You have successfully joined the queue!\n\n**Position:** {position}",
    queue_joined_channel_description: "User joined the queue",
    queue_ready_dm_description: "**Your spot is ready!** You are now at the top of the queue.",
    queue_ready_dm_join_hint: "Click the button below to join the server.",
    queue_ready_channel_description: "User reached position #1 in queue",
    queue_position_dm_description: "You are now in the **top {milestone}** of the queue! Get ready to join the server soon.",
    queue_kicked_dm_description: "You have been **removed from the queue** by a moderator.",
    queue_kicked_reason: "**Reason:** {reason}",
    application_submitted_dm_description: "Your application for **{application_title}** has been submitted successfully!",
    application_submitted_channel_description: "A new application has been submitted for **{application_title}**",
    application_cosign_required_title: "Application Co-sign Required",
    application_cosign_required_description: "An application for **{application_title}** is awaiting a second staff approval.",
    application_accepted_dm_title: "Application Accepted!",
    application_accepted_dm_description: "Congratulations! Your application for **{application_title}** has been **accepted**!",
    application_accepted_channel_title: "Application Accepted",
    application_accepted_channel_description: "An application for **{application_title}** has been accepted!",
    application_rejected_dm_title: "Application Rejected",
    application_rejected_dm_description: "Unfortunately, your application for **{application_title}** has been **rejected**.",
    application_rejected_channel_title: "Application Rejected",
    application_rejected_channel_description: "An application for **{application_title}** has been rejected.",
    ticket_created_dm_title: "Ticket Created",
    ticket_created_dm_description: "Your support ticket has been created successfully!\n\n**{ticket_title}**",
    ticket_created_on_behalf_dm_description: "A staff member opened this support ticket on your behalf.\n\n**{ticket_title}**",
    ticket_created_channel_title: "New Support Ticket",
    ticket_created_channel_description: "**{ticket_title}**",
    ticket_reply_dm_title: "New Reply on Your Ticket",
    ticket_reply_dm_description: "You have a new reply on ticket **#{ticket_id}: {ticket_title}**",
    ticket_reply_channel_title: "Ticket Reply",
    ticket_reply_channel_description: "New reply on ticket **#{ticket_id}: {ticket_title}**",
    ticket_closed_dm_title: "Ticket Updated",
    ticket_closed_dm_description: "Your support ticket **#{ticket_id}: {ticket_title}** has been marked **{status}**.",
    ticket_closed_channel_title: "Ticket Closed",
    ticket_closed_channel_description: "Ticket **#{ticket_id}: {ticket_title}** was marked **{status}**.",
    ticket_escalated_dm_title: "Ticket Escalated",
    ticket_escalated_dm_description: "Ticket **#{ticket_id}: {ticket_title}** has been escalated for owner review.",
    ticket_escalated_channel_title: "Ticket Escalated",
    ticket_escalated_channel_description: "Ticket **#{ticket_id}: {ticket_title}** was escalated for owner review.",
    ticket_overdue_title: "Ticket Overdue",
    ticket_overdue_description: "Ticket **#{ticket_id}: {ticket_title}** has exceeded its SLA response window.",
    ticket_auto_closed_title: "Ticket Auto-Closed",
    ticket_auto_closed_description: "Your support ticket has been automatically closed due to inactivity.\n\n**{ticket_title}**",
    ticket_invitation_title: "Ticket Invitation",
    ticket_invitation_description: "You've been invited to ticket **#{ticket_id}: {ticket_title}**.",
    ticket_rating_prompt: "Please rate your support experience using the button below.",
  },
};

export type TranslationKeys = typeof en;
export default en;
