import type { TranslationKeys } from "./eng";

const es: TranslationKeys = {
  // Common
  common: {
    save: "Guardar",
    cancel: "Cancelar",
    delete: "Eliminar",
    edit: "Editar",
    back: "Volver",
    loading: "Cargando...",
    confirm: "Confirmar",
    yes: "Sí",
    no: "No",
    enabled: "Habilitado",
    disabled: "Deshabilitado",
    configured: "Configurado",
    not_configured: "Sin configurar",
    coming_soon: "Próximamente",
    available: "Disponible",
    click_to_manage: "Clic para gestionar",
    click_to_setup: "Clic para configurar",
    click_to_customize: "Clic para personalizar",
    required: "Obligatorio",
    optional: "Opcional",
    search: "Buscar",
    no_results: "Sin resultados",
    error: "Algo salió mal",
    success: "Éxito",
  },

  // Navigation / Sidebar
  nav: {
    dashboard: "Panel",
    queue: "Cola",
    tickets: "Tickets",
    applications: "Solicitudes",
    settings: "Ajustes",
    logout: "Cerrar sesión",
    customer_dashboard: "Panel del cliente",
    view_queue_panel: "Ver panel de cola",
    view_queue_panel_hint: "Previsualiza el panel de cola para comprobar cómo los ajustes afectan solicitudes, tickets y la vista de cola.",
  },

  // Auth
  auth: {
    login: "Iniciar sesión con Discord",
    logout: "Cerrar sesión",
    login_description: "Inicia sesión con tu cuenta de Discord para continuar",
  },

  // API errors
  errors: {
    unauthorized: "Usuario no autenticado",
    forbidden: "Prohibido",
    insufficient_permissions: "No tienes permiso para realizar esta acción",
    bad_request: "Solicitud inválida",
    invalid_request: "Solicitud inválida",
    invalid_request_body: "Cuerpo de solicitud inválido",
    internal_error: "Error interno del servidor",
    not_found: "Recurso no encontrado",
    conflict: "Esta acción entra en conflicto con el estado actual",
    owner_required: "Solo el cliente puede actualizar esta configuración",
    language_update_failed: "No se pudo guardar la configuración de idioma",
    language_retrieval_failed: "No se pudo cargar la configuración de idioma",
    queue_disabled: "El módulo de cola está desactivado",
    queue_locked: "La cola está bloqueada",
    queue_staff_only_locked: "La cola está actualmente limitada al personal",
    discord_config_required: "Configura primero la integración de Discord",
    customer_session_required: "Se requiere una sesión de cliente para cambiar de panel.",
    customer_session_check_failed: "No se pudo verificar tu sesión de cliente.",
    steam_required: "Se requiere vincular una cuenta de Steam antes de unirse a esta cola",
    steam_banned: "Esta cuenta de Steam tiene prohibido unirse a esta cola",
    discord_banned: "Esta cuenta de Discord tiene prohibido unirse a esta cola",
    steam_recently_changed: "Tu cuenta de Steam se cambió recientemente y debe esperar antes de unirse a esta cola",
    steam_unlink_disabled: "Este servidor no permite desvincular Steam",
  },

  // Steam identity
  steam_identity: {
    title: "Identidad de Steam",
    description: "Vincula Steam para ayudar a los servidores a verificar el acceso a la cola y desalentar el uso de cuentas alternativas para evadir baneos.",
    linked: "Steam vinculado",
    not_linked: "No hay cuenta de Steam vinculada",
    link: "Vincular Steam",
    unlink: "Desvincular Steam",
    recently_changed: "Cambio reciente",
    change_history: "Historial de cambios de Steam",
    required_title: "Cuenta de Steam requerida",
    required_description: "Este servidor requiere una cuenta de Steam vinculada antes de unirse a la cola.",
  },

  // txAdmin bans
  txadmin_bans: {
    title: "Sincronización de baneos de txAdmin",
    description: "Obtén identificadores baneados de Steam y Discord desde txAdmin playersDB.json, actualiza durante los ingresos a la cola y acepta envíos en vivo de baneos/desbaneos desde eventos de txAdmin.",
    sync_now: "Sincronizar ahora",
    sync_success: "Sincronización de baneos completada",
    sync_failed: "No se pudieron sincronizar los baneos desde el recurso del servidor",
    active_bans: "Identificadores baneados activos",
    last_manual_sync: "Última sincronización manual",
    last_server_push: "Último envío del servidor",
    never: "Nunca",
    resource_config: "Configuración de envío del recurso del servidor",
  },

  // Customer dashboard
  customer: {
    welcome: "Bienvenido de nuevo, {name}!",
    subtitle: "Gestiona la configuración de tu servidor FiveM y la cola.",
    setup_progress: "Progreso de configuración",
    required_completed: "{completed} de {total} elementos obligatorios completados",
    completed: "Completado",
    remaining: "Pendiente",
    all_completed: "¡Todos los elementos obligatorios completados!",
    done: "Listo",

    // Section headers
    essential_setup: "Configuración esencial",
    discord_configuration: "Configuración de Discord",
    features: "Funciones",
    branding: "Marca",

    // Essential setup cards
    fivem_title: "Configuración de API FiveM",
    fivem_desc_done: "Tu servidor FiveM está configurado y listo para gestionar la cola.",
    fivem_desc_pending: "Configura tu API de FiveM para habilitar la gestión de la cola.",

    discord_title: "Configuración de Discord",
    discord_desc_done: "Tu bot de Discord está configurado y listo para gestionar la cola.",
    discord_desc_pending: "Configura el token de tu bot de Discord y el ID del servidor.",

    tebex_title: "Configuración de API Tebex",
    tebex_desc_done: "Tu API de Tebex está configurada y lista para el seguimiento de pagos.",
    tebex_desc_pending: "Configura tu clave de API de Tebex para habilitar el historial de compras.",

    // Discord configuration cards
    dashboard_roles_title: "Configuración de roles del panel",
    dashboard_roles_desc: "Configura qué roles de Discord pueden acceder al panel y unirse a la cola.",
    dashboard_roles_locked: "Completa la configuración de Discord primero para configurar los roles de acceso al panel.",

    queue_roles_title: "Constructor de cola",
    queue_roles_desc: "Configura roles de prioridad, slots de bypass, reglas de acceso y comportamiento de la tarjeta nativa.",
    queue_roles_desc_done: "Tus roles de cola y flujo de acceso están configurados.",
    queue_roles_locked: "Completa la configuración de Discord primero para configurar reglas y acceso de cola.",

    moderators_title: "Moderadores",
    moderators_desc: "Añade moderadores para ayudar a gestionar tickets y solicitudes de tu servidor.",
    moderators_desc_done: "Tienes moderadores con acceso a tickets y solicitudes.",
    moderators_locked: "Completa la configuración de Discord primero para gestionar moderadores.",
    discord_required: "Completa la configuración de Discord primero",

    // Features cards
    module_settings_title: "Ajustes de módulos",
    module_settings_desc: "Habilita o deshabilita módulos de solicitudes, tickets, notificaciones y personal.",

    application_builder_title: "Constructor de solicitudes",
    application_builder_desc: "Crea y gestiona formularios de solicitud con preguntas personalizadas para los jugadores.",

    tickets_title: "Tickets",
    tickets_desc: "Gestiona categorías de tickets y personaliza tu sistema de soporte para jugadores y moderadores.",

    notifications_title: "Notificaciones de Discord",
    notifications_desc: "Configura notificaciones de Discord para la cola, solicitudes y tickets",

    queue_builder_title: "Constructor de cola",
    queue_builder_desc: "Construye y personaliza tu sistema de cola con reglas avanzadas, prioridades y automatización.",

    language_title: "Idioma",
    language_desc: "Configura el idioma de la interfaz para los jugadores.",

    // Branding cards
    app_customization_title: "Personalización de la app",
    app_customization_desc: "Personaliza ajustes de toda la app como el color principal que se aplica a toda la aplicación.",

    dashboard_customization_title: "Personalización del panel",
    dashboard_customization_desc: "Personaliza el logo del panel que verán tú y todos los jugadores/moderadores.",

    home_page_title: "Personalización de la página de inicio",
    home_page_desc: "Personaliza la apariencia, el contenido y los enlaces rápidos de tu página de inicio para los jugadores.",

    login_customization_title: "Personalización del inicio de sesión",
    login_customization_desc: "Personaliza la apariencia, la marca y el flujo de autenticación de tu página de inicio de sesión.",

    custom_domain_title: "Dominio personalizado",
    custom_domain_desc_done: "Tu dominio personalizado está configurado y listo para usar.",
    custom_domain_desc_pending: "Configura un dominio personalizado para usar tu propio nombre de dominio en tu página de inicio.",
  },

  // Language settings page
  language: {
    title: "Idioma",
    description: "Configura el idioma de la interfaz para los jugadores.",
    select_label: "Idioma de la interfaz",
    select_description: "Esto controla el idioma que ven los jugadores al usar tu cola, tickets y solicitudes.",
    select_language: "Seleccionar idioma",
    select_language_description: "Elige el idioma que verán los jugadores al usar tu cola, tickets y solicitudes.",
    customize_title: "Personalizar traducciones",
    customize_description: "Edita el contenido de traducción usado por tu configuración. Mantén las claves y los marcadores intactos.",
    download: "Descargar archivo de traducción",
    reset: "Restablecer valores",
    save_success: "Idioma guardado correctamente",
    save_error: "Error al guardar el idioma",
    invalid_json: "Las traducciones deben ser JSON válido",
    mode_label: "Fuente del idioma",
    mode_preset: "Predeterminado",
    mode_custom: "Personalizado",
    preset_description: "Usa uno de los archivos de traducción incluidos y mantenidos por el repositorio público de idiomas.",
    custom_description: "Usa el JSON de traducción específico de este cliente para esta configuración.",
    english: "Inglés",
    spanish: "Español",
    norwegian: "Noruego",
  },

  // Queue
  queue: {
    title: "Cola",
    position: "Posición",
    join: "Unirse a la cola",
    leave: "Salir de la cola",
    players_in_queue: "{count} jugadores en cola",
    your_position: "Tu posición: {position}",
    estimated_wait: "Espera estimada: {time}",
    queue_closed: "La cola está cerrada",
    queue_open: "La cola está abierta",
  },

  // Tickets
  tickets: {
    title: "Tickets",
    create: "Crear ticket",
    open: "Abierto",
    closed: "Cerrado",
    no_tickets: "Sin tickets",
    subject: "Asunto",
    description: "Descripción",
    status: "Estado",
    created_at: "Creado",
    updated_at: "Última actualización",
    close_ticket: "Cerrar ticket",
    ticket_closed: "Ticket cerrado",
    message_placeholder: "Escribe tu mensaje...",
    send: "Enviar",
    create_modal_title: "Crear nuevo ticket",
    create_success: "Ticket creado correctamente!",
    create_error: "No se pudo crear el ticket. Inténtalo de nuevo.",
    related_title: "Tickets relacionados",
    related_count: "{count} ticket{plural} vinculado{plural}",
    related_search_label: "Buscar por ID de ticket",
    related_link: "Vincular",
    related_linked: "Ticket relacionado vinculado",
    related_link_failed: "No se pudo vincular el ticket relacionado",
    related_removed: "Ticket relacionado eliminado",
    related_remove_failed: "No se pudo eliminar el ticket relacionado",
    related_loading: "Cargando ticket...",
    related_none_found: "No se encontró un ticket vinculable para ese ID.",
    related_none_linked: "No hay tickets relacionados vinculados.",
    related_remove: "Eliminar",
    watcher_started: "Viendo ticket",
    watcher_stopped: "Dejaste de ver el ticket",
    watcher_dm_description: "Recibe un DM cuando alguien responda a este ticket.",
  },

  // Applications
  applications: {
    title: "Solicitudes",
    submit: "Enviar solicitud",
    no_applications: "No hay solicitudes disponibles",
    submitted: "Solicitud enviada correctamente",
    already_submitted: "Ya enviaste esta solicitud",
    status: "Estado",
    pending: "Pendiente",
    approved: "Aprobada",
    rejected: "Rechazada",
    rejected_success: "Solicitud rechazada",
    cosigned_success: "Solicitud cofirmada",
    no_internal_notes: "Aún no hay notas internas.",
  },

  // Discord notifications
  discord_notifications: {
    field_ticket_id: "ID del ticket",
    field_priority: "Prioridad",
    field_status: "Estado",
    field_created_by: "Creado por",
    field_opened_for: "Abierto para",
    field_category: "Categoría",
    field_description: "Descripción",
    field_from: "De",
    field_reply: "Respuesta",
    field_ticket: "Ticket",
    field_user: "Usuario",
    field_reason: "Motivo",
    field_created: "Creado",
    field_assigned_to: "Asignado a",
    field_escalated_by: "Escalado por",
    field_invited_by: "Invitado por",
    field_queue_block: "Bloqueo de cola",
    button_rate_experience: "Valora tu experiencia",
    auto_closed_footer: "Si todavía necesitas ayuda, abre un nuevo ticket.",
    closed_status: "Cerrado",
    yes: "Sí",
    no: "No",
    queue_joined_dm_description: "¡Te has unido a la cola con éxito!\n\n**Posición:** {position}",
    queue_joined_channel_description: "El usuario se unió a la cola",
    queue_ready_dm_description: "**¡Tu lugar está listo!** Ahora estás al frente de la cola.",
    queue_ready_dm_join_hint: "Haz clic en el botón de abajo para unirte al servidor.",
    queue_ready_channel_description: "El usuario alcanzó la posición n.º 1 en la cola",
    queue_position_dm_description: "¡Ahora estás en el **top {milestone}** de la cola! Prepárate para unirte al servidor pronto.",
    queue_kicked_dm_description: "Has sido **eliminado de la cola** por un moderador.",
    queue_kicked_reason: "**Motivo:** {reason}",
    application_submitted_dm_description: "¡Tu solicitud para **{application_title}** ha sido enviada con éxito!",
    application_submitted_channel_description: "Se ha enviado una nueva solicitud para **{application_title}**",
    application_cosign_required_title: "Se requiere co-firma de solicitud",
    application_cosign_required_description: "Una solicitud para **{application_title}** está esperando una segunda aprobación del personal.",
    application_accepted_dm_title: "¡Solicitud aceptada!",
    application_accepted_dm_description: "¡Felicidades! Tu solicitud para **{application_title}** ha sido **aceptada**.",
    application_accepted_channel_title: "Solicitud aceptada",
    application_accepted_channel_description: "Una solicitud para **{application_title}** ha sido aceptada.",
    application_rejected_dm_title: "Solicitud rechazada",
    application_rejected_dm_description: "Lamentablemente, tu solicitud para **{application_title}** ha sido **rechazada**.",
    application_rejected_channel_title: "Solicitud rechazada",
    application_rejected_channel_description: "Una solicitud para **{application_title}** ha sido rechazada.",
    ticket_created_dm_title: "Ticket creado",
    ticket_created_dm_description: "¡Tu ticket de soporte ha sido creado con éxito!\n\n**{ticket_title}**",
    ticket_created_on_behalf_dm_description: "Un miembro del personal abrió este ticket de soporte en tu nombre.\n\n**{ticket_title}**",
    ticket_created_channel_title: "Nuevo ticket de soporte",
    ticket_created_channel_description: "**{ticket_title}**",
    ticket_reply_dm_title: "Nueva respuesta en tu ticket",
    ticket_reply_dm_description: "Tienes una nueva respuesta en el ticket **#{ticket_id}: {ticket_title}**",
    ticket_reply_channel_title: "Respuesta al ticket",
    ticket_reply_channel_description: "Nueva respuesta en el ticket **#{ticket_id}: {ticket_title}**",
    ticket_closed_dm_title: "Ticket actualizado",
    ticket_closed_dm_description: "Tu ticket de soporte **#{ticket_id}: {ticket_title}** ha sido marcado como **{status}**.",
    ticket_closed_channel_title: "Ticket cerrado",
    ticket_closed_channel_description: "El ticket **#{ticket_id}: {ticket_title}** fue marcado como **{status}**.",
    ticket_escalated_dm_title: "Ticket escalado",
    ticket_escalated_dm_description: "El ticket **#{ticket_id}: {ticket_title}** ha sido escalado para revisión del propietario.",
    ticket_escalated_channel_title: "Ticket escalado",
    ticket_escalated_channel_description: "El ticket **#{ticket_id}: {ticket_title}** fue escalado para revisión del propietario.",
    ticket_overdue_title: "Ticket vencido",
    ticket_overdue_description: "El ticket **#{ticket_id}: {ticket_title}** ha superado su ventana de respuesta SLA.",
    ticket_auto_closed_title: "Ticket cerrado automáticamente",
    ticket_auto_closed_description: "Tu ticket de soporte ha sido cerrado automáticamente por inactividad.\n\n**{ticket_title}**",
    ticket_invitation_title: "Invitación a ticket",
    ticket_invitation_description: "Has sido invitado al ticket **#{ticket_id}: {ticket_title}**.",
    ticket_rating_prompt: "Por favor, valora tu experiencia de soporte usando el botón de abajo.",
  },
};

export default es;
