import type { TranslationKeys } from "./eng";

const fr: TranslationKeys = {
  // Common
  common: {
    save: "Enregistrer",
    cancel: "Annuler",
    delete: "Supprimer",
    edit: "Modifier",
    back: "Retour",
    loading: "Chargement...",
    confirm: "Confirmer",
    yes: "Oui",
    no: "Non",
    enabled: "Activé",
    disabled: "Désactivé",
    configured: "Configuré",
    not_configured: "Non configuré",
    coming_soon: "À venir",
    available: "Disponible",
    click_to_manage: "Cliquez pour gérer",
    click_to_setup: "Cliquez pour configurer",
    click_to_customize: "Cliquez pour personnaliser",
    required: "Obligatoire",
    optional: "Facultatif",
    search: "Rechercher",
    no_results: "Aucun résultat trouvé",
    error: "Une erreur est survenue",
    success: "Succès",
  },

  // Navigation / Sidebar
  nav: {
    dashboard: "Tableau de bord",
    queue: "File d'attente",
    tickets: "Tickets",
    applications: "Candidatures",
    settings: "Paramètres",
    logout: "Déconnexion",
    customer_dashboard: "Tableau de bord client",
    view_queue_panel: "Voir le panneau de file d'attente",
    view_queue_panel_hint: "Prévisualisez le panneau de file d'attente pour vérifier l'effet des paramètres sur les candidatures, les tickets et la vue de file.",
  },

  // Auth
  auth: {
    login: "Connexion avec Discord",
    logout: "Déconnexion",
    login_description: "Connectez-vous avec votre compte Discord pour continuer",
  },

  // API errors
  errors: {
    unauthorized: "Utilisateur non authentifié",
    forbidden: "Interdit",
    insufficient_permissions: "Vous n'avez pas l'autorisation d'effectuer cette action",
    bad_request: "Requête invalide",
    invalid_request: "Requête invalide",
    invalid_request_body: "Corps de requête invalide",
    internal_error: "Erreur interne du serveur",
    not_found: "Ressource introuvable",
    conflict: "Cette action entre en conflit avec l'état actuel",
    owner_required: "Seul le client peut modifier ce paramètre",
    language_update_failed: "Impossible d'enregistrer les paramètres de langue",
    language_retrieval_failed: "Impossible de charger les paramètres de langue",
    queue_disabled: "Le module de file d'attente est actuellement désactivé",
    queue_locked: "La file d'attente est actuellement verrouillée",
    queue_staff_only_locked: "La file d'attente est actuellement réservée au personnel",
    discord_config_required: "Configurez d'abord l'intégration Discord",
    customer_session_required: "Session client requise pour changer de panneau.",
    customer_session_check_failed: "Impossible de vérifier votre session client.",
    steam_required: "La liaison d'un compte Steam est requise avant de rejoindre cette file d'attente",
    steam_banned: "Ce compte Steam est banni de cette file d'attente",
    discord_banned: "Ce compte Discord est banni de cette file d'attente",
    steam_recently_changed: "Votre compte Steam a été modifié récemment et doit attendre avant de rejoindre cette file d'attente",
    steam_unlink_disabled: "La dissociation Steam est désactivée pour ce serveur",
  },

  // Steam identity
  steam_identity: {
    title: "Identité Steam",
    description: "Associez Steam pour aider les serveurs à vérifier l'accès à la file d'attente et décourager le contournement des bannissements par comptes alternatifs.",
    linked: "Steam associé",
    not_linked: "Aucun compte Steam associé",
    link: "Associer Steam",
    unlink: "Dissocier Steam",
    recently_changed: "Modifié récemment",
    change_history: "Historique des changements Steam",
    required_title: "Compte Steam requis",
    required_description: "Ce serveur exige un compte Steam associé avant de rejoindre la file d'attente.",
  },

  // txAdmin bans
  txadmin_bans: {
    title: "Synchronisation des bannissements txAdmin",
    description: "Récupérez les identifiants de bannissement Steam et Discord depuis playersDB.json de txAdmin, actualisez-les lors des entrées en file d'attente et acceptez les notifications de bannissement/débannissement en direct depuis les événements txAdmin.",
    sync_now: "Synchroniser maintenant",
    sync_success: "Synchronisation des bannissements terminée",
    sync_failed: "Impossible de synchroniser les bannissements depuis la ressource serveur",
    active_bans: "Identifiants de bannissement actifs",
    last_manual_sync: "Dernière synchronisation manuelle",
    last_server_push: "Dernière notification serveur",
    never: "Jamais",
    resource_config: "Configuration de synchronisation de la ressource serveur",
  },

  // Customer dashboard
  customer: {
    welcome: "Bienvenue, {name}!",
    subtitle: "Gérez la configuration de votre serveur FiveM et les paramètres de file d'attente.",
    setup_progress: "Progression de la configuration",
    required_completed: "{completed} sur {total} éléments obligatoires terminés",
    completed: "Terminé",
    remaining: "Restant",
    all_completed: "Tous les éléments obligatoires sont terminés!",
    done: "Fait",
    essential_setup: "Configuration essentielle",
    discord_configuration: "Configuration Discord",
    features: "Fonctionnalités",
    branding: "Image de marque",
    fivem_title: "Configuration de l'API FiveM",
    fivem_desc_done: "Votre serveur FiveM est configuré et prêt pour la gestion de la file d'attente.",
    fivem_desc_pending: "Configurez vos paramètres d'API FiveM pour activer la gestion de la file d'attente.",
    discord_title: "Configuration Discord",
    discord_desc_done: "Votre bot Discord est configuré et prêt pour la gestion de la file d'attente.",
    discord_desc_pending: "Configurez le jeton de votre bot Discord et l'ID du serveur pour la gestion de la file d'attente.",
    tebex_title: "Configuration de l'API Tebex",
    tebex_desc_done: "Votre API Tebex est configurée et prête pour le suivi des paiements.",
    tebex_desc_pending: "Configurez votre clé d'API Tebex pour activer le suivi de l'historique des achats.",
    dashboard_roles_title: "Configuration des rôles du tableau de bord",
    dashboard_roles_desc: "Configurez les rôles Discord qui peuvent accéder au tableau de bord et rejoindre la file d'attente.",
    dashboard_roles_locked: "Terminez d'abord la configuration Discord pour configurer les rôles d'accès au tableau de bord et à la file d'attente.",
    queue_roles_title: "Créateur de file d'attente",
    queue_roles_desc: "Configurez les rôles prioritaires, les emplacements de contournement, les règles d'accès et le comportement des cartes natives.",
    queue_roles_desc_done: "Vos rôles de file d'attente et votre flux d'accès sont configurés.",
    queue_roles_locked: "Terminez d'abord la configuration Discord pour configurer les règles de file d'attente et l'accès.",
    moderators_title: "Modérateurs",
    moderators_desc: "Ajoutez des modérateurs pour aider à gérer les tickets et les candidatures de votre serveur.",
    moderators_desc_done: "Vous avez des modérateurs avec accès aux tickets et aux candidatures.",
    moderators_locked: "Terminez d'abord la configuration Discord pour gérer les modérateurs.",
    discord_required: "Terminez d'abord la configuration Discord",
    module_settings_title: "Paramètres des modules",
    module_settings_desc: "Activez ou désactivez les modules de candidatures, tickets, notifications et outils destinés au personnel.",
    application_builder_title: "Créateur de candidatures",
    application_builder_desc: "Créez et gérez des formulaires de candidature avec des questions personnalisées à remplir par les joueurs.",
    tickets_title: "Tickets",
    tickets_desc: "Gérez les catégories de tickets et personnalisez votre système d'assistance pour les joueurs et les modérateurs.",
    notifications_title: "Notifications Discord",
    notifications_desc: "Configurez les notifications Discord pour la file d'attente, les candidatures et les tickets",
    queue_builder_title: "Créateur de file d'attente",
    queue_builder_desc: "Créez et personnalisez votre système de file d'attente avec des règles avancées, des priorités et des fonctions d'automatisation.",
    language_title: "Langue",
    language_desc: "Définissez la langue de l'interface destinée aux joueurs.",
    app_customization_title: "Personnalisation de l'application",
    app_customization_desc: "Personnalisez les paramètres globaux comme la couleur principale appliquée à toute l'application.",
    dashboard_customization_title: "Personnalisation du tableau de bord",
    dashboard_customization_desc: "Personnalisez le logo de la barre de navigation du tableau de bord visible par vous ainsi que par tous les joueurs et modérateurs.",
    home_page_title: "Personnalisation de la page d'accueil",
    home_page_desc: "Personnalisez l'apparence, le contenu et les liens rapides de votre page d'accueil pour les joueurs.",
    login_customization_title: "Personnalisation de la connexion",
    login_customization_desc: "Personnalisez l'apparence, l'image de marque et le flux d'authentification de votre page de connexion.",
    custom_domain_title: "Domaine personnalisé",
    custom_domain_desc_done: "Votre domaine personnalisé est configuré et prêt à être utilisé.",
    custom_domain_desc_pending: "Configurez un domaine personnalisé pour utiliser votre propre nom de domaine pour votre page d'accueil.",
  },

  // Language settings page
  language: {
    title: "Langue",
    description: "Définissez la langue de l'interface destinée aux joueurs.",
    select_label: "Langue de l'interface",
    select_description: "Cela contrôle la langue que les joueurs voient lorsqu'ils utilisent votre file d'attente, vos tickets et vos candidatures.",
    select_language: "Sélectionner la langue",
    select_language_description: "Choisissez la langue que les joueurs verront lorsqu'ils utiliseront votre file d'attente, vos tickets et vos candidatures.",
    customize_title: "Remplacements de traduction",
    customize_description: "Modifiez le contenu de traduction utilisé par votre configuration. Conservez les clés et les espaces réservés intacts.",
    download: "Télécharger le fichier de traduction",
    reset: "Réinitialiser par défaut",
    save_success: "Langue enregistrée avec succès",
    save_error: "Impossible d'enregistrer la langue",
    invalid_json: "Les traductions doivent être du JSON valide",
    mode_label: "Source de langue",
    mode_preset: "Prédéfinie",
    mode_custom: "Personnalisée",
    preset_description: "Utilisez l'un des fichiers de traduction inclus maintenus par le dépôt public de langues.",
    custom_description: "Utilisez le JSON de traduction propre à ce client ci-dessous pour cette configuration.",
    english: "Anglais",
    spanish: "Espagnol",
    norwegian: "Norvégien",
  },

  // Queue
  queue: {
    title: "File d'attente",
    position: "Position",
    join: "Rejoindre la file d'attente",
    leave: "Quitter la file d'attente",
    players_in_queue: "{count} joueurs en file d'attente",
    your_position: "Votre position : {position}",
    estimated_wait: "Attente estimée : {time}",
    queue_closed: "La file d'attente est fermée",
    queue_open: "La file d'attente est ouverte",
  },

  // Tickets
  tickets: {
    title: "Tickets",
    create: "Créer un ticket",
    open: "Ouvert",
    closed: "Fermé",
    no_tickets: "Aucun ticket pour le moment",
    subject: "Sujet",
    description: "Description",
    status: "Statut",
    created_at: "Créé",
    updated_at: "Dernière mise à jour",
    close_ticket: "Fermer le ticket",
    ticket_closed: "Ticket fermé",
    message_placeholder: "Tapez votre message...",
    send: "Envoyer",
    create_modal_title: "Créer un nouveau ticket",
    create_success: "Ticket créé avec succès!",
    create_error: "Impossible de créer le ticket. Veuillez réessayer.",
    related_title: "Tickets associés",
    related_count: "{count} ticket{plural} lié{plural}",
    related_search_label: "Rechercher par ID de ticket",
    related_link: "Lier",
    related_linked: "Ticket associé lié",
    related_link_failed: "Impossible de lier le ticket associé",
    related_removed: "Ticket associé retiré",
    related_remove_failed: "Impossible de retirer le ticket associé",
    related_loading: "Chargement du ticket...",
    related_none_found: "Aucun ticket pouvant être lié n'a été trouvé pour cet ID.",
    related_none_linked: "Aucun ticket associé lié.",
    related_remove: "Retirer",
    watcher_started: "Surveillance du ticket activée",
    watcher_stopped: "Surveillance du ticket arrêtée",
    watcher_dm_description: "Recevez un message privé lorsqu'une personne répond à ce ticket.",
  },

  // Applications
  applications: {
    title: "Candidatures",
    submit: "Soumettre une candidature",
    no_applications: "Aucune candidature disponible",
    submitted: "Candidature soumise avec succès",
    already_submitted: "Vous avez déjà soumis cette candidature",
    status: "Statut",
    pending: "En attente",
    approved: "Approuvée",
    rejected: "Rejetée",
    rejected_success: "Candidature rejetée",
    cosigned_success: "Candidature co-signée",
    no_internal_notes: "Aucune note interne pour le moment.",
  },

  // Discord notifications
  discord_notifications: {
    field_ticket_id: "ID du ticket",
    field_priority: "Priorité",
    field_status: "Statut",
    field_created_by: "Créé par",
    field_opened_for: "Ouvert pour",
    field_category: "Catégorie",
    field_description: "Description",
    field_from: "De",
    field_reply: "Réponse",
    field_ticket: "Ticket",
    field_user: "Utilisateur",
    field_reason: "Raison",
    field_created: "Créé",
    field_assigned_to: "Assigné à",
    field_escalated_by: "Escaladé par",
    field_invited_by: "Invité par",
    field_queue_block: "Blocage de file",
    button_rate_experience: "Évaluer votre expérience",
    auto_closed_footer: "Si vous avez encore besoin d'aide, veuillez ouvrir un nouveau ticket.",
    closed_status: "Fermé",
    yes: "Oui",
    no: "Non",
    queue_joined_dm_description: "Vous avez rejoint la file d'attente avec succès!\n\n**Position :** {position}",
    queue_joined_channel_description: "L'utilisateur a rejoint la file d'attente",
    queue_ready_dm_description: "**Votre place est prête!** Vous êtes maintenant en tête de la file d'attente.",
    queue_ready_dm_join_hint: "Cliquez sur le bouton ci-dessous pour rejoindre le serveur.",
    queue_ready_channel_description: "L'utilisateur a atteint la position n°1 dans la file d'attente",
    queue_position_dm_description: "Vous êtes maintenant dans le **top {milestone}** de la file d'attente! Préparez-vous à rejoindre bientôt le serveur.",
    queue_kicked_dm_description: "Vous avez été **retiré de la file d'attente** par un modérateur.",
    queue_kicked_reason: "**Raison :** {reason}",
    application_submitted_dm_description: "Votre candidature pour **{application_title}** a bien été soumise!",
    application_submitted_channel_description: "Une nouvelle candidature a été soumise pour **{application_title}**",
    application_cosign_required_title: "Co-signature de candidature requise",
    application_cosign_required_description: "Une candidature pour **{application_title}** attend une deuxième approbation du personnel.",
    application_accepted_dm_title: "Candidature acceptée!",
    application_accepted_dm_description: "Félicitations! Votre candidature pour **{application_title}** a été **acceptée**!",
    application_accepted_channel_title: "Candidature acceptée",
    application_accepted_channel_description: "Une candidature pour **{application_title}** a été acceptée!",
    application_rejected_dm_title: "Candidature rejetée",
    application_rejected_dm_description: "Malheureusement, votre candidature pour **{application_title}** a été **rejetée**.",
    application_rejected_channel_title: "Candidature rejetée",
    application_rejected_channel_description: "Une candidature pour **{application_title}** a été rejetée.",
    ticket_created_dm_title: "Ticket créé",
    ticket_created_dm_description: "Votre ticket d'assistance a été créé avec succès!\n\n**{ticket_title}**",
    ticket_created_on_behalf_dm_description: "Un membre du personnel a ouvert ce ticket d'assistance en votre nom.\n\n**{ticket_title}**",
    ticket_created_channel_title: "Nouveau ticket d'assistance",
    ticket_created_channel_description: "**{ticket_title}**",
    ticket_reply_dm_title: "Nouvelle réponse à votre ticket",
    ticket_reply_dm_description: "Vous avez une nouvelle réponse sur le ticket **#{ticket_id}: {ticket_title}**",
    ticket_reply_channel_title: "Réponse au ticket",
    ticket_reply_channel_description: "Nouvelle réponse sur le ticket **#{ticket_id}: {ticket_title}**",
    ticket_closed_dm_title: "Ticket mis à jour",
    ticket_closed_dm_description: "Votre ticket d'assistance **#{ticket_id}: {ticket_title}** a été marqué **{status}**.",
    ticket_closed_channel_title: "Ticket fermé",
    ticket_closed_channel_description: "Le ticket **#{ticket_id}: {ticket_title}** a été marqué **{status}**.",
    ticket_escalated_dm_title: "Ticket escaladé",
    ticket_escalated_dm_description: "Le ticket **#{ticket_id}: {ticket_title}** a été escaladé pour examen par le propriétaire.",
    ticket_escalated_channel_title: "Ticket escaladé",
    ticket_escalated_channel_description: "Le ticket **#{ticket_id}: {ticket_title}** a été escaladé pour examen par le propriétaire.",
    ticket_overdue_title: "Ticket en retard",
    ticket_overdue_description: "Le ticket **#{ticket_id}: {ticket_title}** a dépassé son délai de réponse SLA.",
    ticket_auto_closed_title: "Ticket fermé automatiquement",
    ticket_auto_closed_description: "Votre ticket d'assistance a été fermé automatiquement en raison d'une inactivité.\n\n**{ticket_title}**",
    ticket_invitation_title: "Invitation à un ticket",
    ticket_invitation_description: "Vous avez été invité au ticket **#{ticket_id}: {ticket_title}**.",
    ticket_rating_prompt: "Veuillez évaluer votre expérience d'assistance à l'aide du bouton ci-dessous.",
  },
};

export default fr;
