import type { TranslationKeys } from "./eng";

const no: TranslationKeys = {
  // Common
  common: {
    save: "Lagre",
    cancel: "Avbryt",
    delete: "Slett",
    edit: "Rediger",
    back: "Tilbake",
    loading: "Laster...",
    confirm: "Bekreft",
    yes: "Ja",
    no: "Nei",
    enabled: "Aktivert",
    disabled: "Deaktivert",
    configured: "Konfigurert",
    not_configured: "Ikke konfigurert",
    coming_soon: "Kommer snart",
    available: "Tilgjengelig",
    click_to_manage: "Klikk for å administrere",
    click_to_setup: "Klikk for å sette opp",
    click_to_customize: "Klikk for å tilpasse",
    required: "Påkrevd",
    optional: "Valgfritt",
    search: "Søk",
    no_results: "Ingen resultater funnet",
    error: "Noe gikk galt",
    success: "Vellykket",
  },

  // Navigation / Sidebar
  nav: {
    dashboard: "Dashbord",
    queue: "Kø",
    tickets: "Billetter",
    applications: "Søknader",
    settings: "Innstillinger",
    logout: "Logg ut",
    customer_dashboard: "Kundedashbord",
    view_queue_panel: "Vis køpanel",
    view_queue_panel_hint: "Forhåndsvis køpanelet for å sjekke hvordan innstillinger påvirker søknader, billetter og køvisningen.",
  },

  // Auth
  auth: {
    login: "Logg inn med Discord",
    logout: "Logg ut",
    login_description: "Logg inn med Discord-kontoen din for å fortsette",
  },

  // API errors
  errors: {
    unauthorized: "Bruker er ikke autentisert",
    forbidden: "Forbudt",
    insufficient_permissions: "Du har ikke tillatelse til å utføre denne handlingen",
    bad_request: "Ugyldig forespørsel",
    invalid_request: "Ugyldig forespørsel",
    invalid_request_body: "Ugyldig forespørselsinnhold",
    internal_error: "Intern serverfeil",
    not_found: "Ressursen ble ikke funnet",
    conflict: "Denne handlingen er i konflikt med gjeldende tilstand",
    owner_required: "Bare kunden kan oppdatere denne innstillingen",
    language_update_failed: "Kunne ikke lagre språkinnstillinger",
    language_retrieval_failed: "Kunne ikke laste språkinnstillinger",
    queue_disabled: "Kømodulen er deaktivert",
    queue_locked: "Køen er låst",
    queue_staff_only_locked: "Køen er kun åpen for staff nå",
    discord_config_required: "Konfigurer Discord-integrasjonen først",
    customer_session_required: "Kundeøkt kreves for å bytte panel.",
    customer_session_check_failed: "Kunne ikke bekrefte kundeøkten din.",
    steam_required: "Steam-konto må kobles før du kan bli med i denne køen",
    steam_banned: "Denne Steam-kontoen er utestengt fra å bli med i denne køen",
    discord_banned: "Denne Discord-kontoen er utestengt fra å bli med i denne køen",
    steam_recently_changed: "Steam-kontoen din ble nylig endret og må vente før du kan bli med i denne køen",
    steam_unlink_disabled: "Steam-frakobling er deaktivert for denne serveren",
  },

  // Steam identity
  steam_identity: {
    title: "Steam-identitet",
    description: "Koble Steam for å hjelpe servere med å bekrefte køtilgang og motvirke omgåelse av utestengelser med alternative kontoer.",
    linked: "Steam koblet",
    not_linked: "Ingen Steam-konto koblet",
    link: "Koble Steam",
    unlink: "Koble fra Steam",
    recently_changed: "Nylig endret",
    change_history: "Steam-endringshistorikk",
    required_title: "Steam-konto kreves",
    required_description: "Denne serveren krever en koblet Steam-konto før du kan bli med i køen.",
  },

  // txAdmin bans
  txadmin_bans: {
    title: "txAdmin ban-synkronisering",
    description: "Hent utestengte Steam- og Discord-identifikatorer fra txAdmin playersDB.json, oppdater ved køinnmeldinger, og motta live ban/unban-push fra txAdmin-hendelser.",
    sync_now: "Synkroniser nå",
    sync_success: "Ban-synkronisering fullført",
    sync_failed: "Kunne ikke synkronisere bans fra serverressursen",
    active_bans: "Aktive utestengte identifikatorer",
    last_manual_sync: "Siste manuelle synkronisering",
    last_server_push: "Siste server-push",
    never: "Aldri",
    resource_config: "Push-konfigurasjon for serverressurs",
  },

  // Customer dashboard
  customer: {
    welcome: "Velkommen tilbake, {name}!",
    subtitle: "Administrer konfigurasjonen av FiveM-serveren din og køinnstillinger.",
    setup_progress: "Oppsettsfremdrift",
    required_completed: "{completed} av {total} påkrevde elementer fullført",
    completed: "Fullført",
    remaining: "Gjenstår",
    all_completed: "Alle påkrevde elementer er fullført!",
    done: "Ferdig",

    // Section headers
    essential_setup: "Grunnleggende oppsett",
    discord_configuration: "Discord-konfigurasjon",
    features: "Funksjoner",
    branding: "Profilering",

    // Essential setup cards
    fivem_title: "FiveM API-konfigurasjon",
    fivem_desc_done: "FiveM-serveren din er konfigurert og klar for køhåndtering.",
    fivem_desc_pending: "Konfigurer FiveM API-innstillingene dine for å aktivere køhåndtering.",

    discord_title: "Discord-oppsett",
    discord_desc_done: "Discord-boten din er konfigurert og klar for køhåndtering.",
    discord_desc_pending: "Konfigurer Discord bot-token og guild ID for køhåndtering.",

    tebex_title: "Tebex API-konfigurasjon",
    tebex_desc_done: "Tebex API-en din er konfigurert og klar for betalingssporing.",
    tebex_desc_pending: "Konfigurer Tebex API-nøkkelen din for å aktivere sporing av kjøpshistorikk.",

    // Discord configuration cards
    dashboard_roles_title: "Oppsett av dashbordroller",
    dashboard_roles_desc: "Konfigurer hvilke Discord-roller som kan få tilgang til dashbordet og bli med i køen.",
    dashboard_roles_locked: "Fullfør Discord-oppsettet først for å konfigurere roller for dashbord- og køtilgang.",

    queue_roles_title: "Købygger",
    queue_roles_desc: "Konfigurer prioriteringsroller, bypass-plasser, tilgangsregler og native card-atferd.",
    queue_roles_desc_done: "Køroller og tilgangsflyt er konfigurert.",
    queue_roles_locked: "Fullfør Discord-oppsettet først for å konfigurere køregler og tilgang.",

    moderators_title: "Moderatorer",
    moderators_desc: "Legg til moderatorer for å hjelpe med å administrere billetter og søknader for serveren din.",
    moderators_desc_done: "Du har moderatorer med tilgang til billetter og søknader.",
    moderators_locked: "Fullfør Discord-oppsettet først for å administrere moderatorer.",
    discord_required: "Fullfør Discord-oppsettet først",

    // Features cards
    module_settings_title: "Modulinnstillinger",
    module_settings_desc: "Aktiver eller deaktiver moduler for søknader, billetter, varsler og staff.",

    application_builder_title: "Søknadsbygger",
    application_builder_desc: "Opprett og administrer søknadsskjemaer med egendefinerte spørsmål som spillere kan fylle ut.",

    tickets_title: "Billetter",
    tickets_desc: "Administrer billettkategorier og tilpass supportsystemet for spillere og moderatorer.",

    notifications_title: "Discord-varsler",
    notifications_desc: "Konfigurer Discord-varsler for kø, søknader og billetter",

    queue_builder_title: "Købygger",
    queue_builder_desc: "Bygg og tilpass køsystemet ditt med avanserte regler, prioriteringer og automatiseringsfunksjoner.",

    language_title: "Språk",
    language_desc: "Sett språket for spillergrensesnittet.",

    // Branding cards
    app_customization_title: "App-tilpasning",
    app_customization_desc: "Tilpass app-innstillinger som primærfarge som gjelder for hele applikasjonen.",

    dashboard_customization_title: "Dashbord-tilpasning",
    dashboard_customization_desc: "Tilpass logoen i dashbordets navigasjonslinje som vil være synlig for deg og alle spillere/moderatorer.",

    home_page_title: "Forside-tilpasning",
    home_page_desc: "Tilpass utseendet, innholdet og hurtiglenkene på landingssiden for spillere.",

    login_customization_title: "Innloggings-tilpasning",
    login_customization_desc: "Tilpass utseendet, profileringen og autentiseringsflyten på innloggingssiden.",

    custom_domain_title: "Egendefinert domene",
    custom_domain_desc_done: "Ditt egendefinerte domene er konfigurert og klart til bruk.",
    custom_domain_desc_pending: "Konfigurer et egendefinert domene for å bruke ditt eget domenenavn for landingssiden.",
  },

  // Language settings page
  language: {
    title: "Språk",
    description: "Sett språket for spillergrensesnittet.",
    select_label: "Grensesnittspråk",
    select_description: "Dette styrer språket spillere ser når de bruker kø, billetter og søknader.",
    select_language: "Velg språk",
    select_language_description: "Velg språket spillere vil se når de bruker kø, billetter og søknader.",
    customize_title: "Tilpass oversettelser",
    customize_description: "Rediger oversettelsesinnholdet som brukes av oppsettet ditt. Behold nøkler og plassholdere uendret.",
    download: "Last ned oversettelsesfil",
    reset: "Tilbakestill til standard",
    save_success: "Språk lagret",
    save_error: "Kunne ikke lagre språk",
    invalid_json: "Oversettelser må være gyldig JSON",
    mode_label: "Språkkilde",
    mode_preset: "Forhåndsvalg",
    mode_custom: "Egendefinert",
    preset_description: "Bruk en av de inkluderte oversettelsesfilene som vedlikeholdes av det offentlige språkarkivet.",
    custom_description: "Bruk kundens egendefinerte oversettelses-JSON for dette oppsettet.",
    english: "Engelsk",
    spanish: "Spansk",
    norwegian: "Norsk",
  },

  // Queue
  queue: {
    title: "Kø",
    position: "Posisjon",
    join: "Bli med i kø",
    leave: "Forlat kø",
    players_in_queue: "{count} spillere i kø",
    your_position: "Din posisjon: {position}",
    estimated_wait: "Estimert ventetid: {time}",
    queue_closed: "Køen er stengt",
    queue_open: "Køen er åpen",
  },

  // Tickets
  tickets: {
    title: "Billetter",
    create: "Opprett billett",
    open: "Åpen",
    closed: "Lukket",
    no_tickets: "Ingen billetter ennå",
    subject: "Emne",
    description: "Beskrivelse",
    status: "Status",
    created_at: "Opprettet",
    updated_at: "Sist oppdatert",
    close_ticket: "Lukk billett",
    ticket_closed: "Billetten er lukket",
    message_placeholder: "Skriv meldingen din...",
    send: "Send",
    create_modal_title: "Opprett ny billett",
    create_success: "Billett opprettet!",
    create_error: "Kunne ikke opprette billett. Prøv igjen.",
    related_title: "Relaterte billetter",
    related_count: "{count} koblet billett{plural}",
    related_search_label: "Søk etter billett-ID",
    related_link: "Koble",
    related_linked: "Relatert billett koblet",
    related_link_failed: "Kunne ikke koble relatert billett",
    related_removed: "Relatert billett fjernet",
    related_remove_failed: "Kunne ikke fjerne relatert billett",
    related_loading: "Laster billett...",
    related_none_found: "Fant ingen billett som kan kobles for denne ID-en.",
    related_none_linked: "Ingen relaterte billetter koblet.",
    related_remove: "Fjern",
    watcher_started: "Følger billett",
    watcher_stopped: "Følger ikke lenger billett",
    watcher_dm_description: "Motta DM når noen svarer på denne billetten.",
  },

  // Applications
  applications: {
    title: "Søknader",
    submit: "Send søknad",
    no_applications: "Ingen søknader tilgjengelig",
    submitted: "Søknad sendt",
    already_submitted: "Du har allerede sendt denne søknaden",
    status: "Status",
    pending: "Avventer",
    approved: "Godkjent",
    rejected: "Avvist",
    rejected_success: "Søknad avvist",
    cosigned_success: "Søknad medsignert",
    no_internal_notes: "Ingen interne notater ennå.",
  },

  // Discord notifications
  discord_notifications: {
    field_ticket_id: "Billett-ID",
    field_priority: "Prioritet",
    field_status: "Status",
    field_created_by: "Opprettet av",
    field_opened_for: "Åpnet for",
    field_category: "Kategori",
    field_description: "Beskrivelse",
    field_from: "Fra",
    field_reply: "Svar",
    field_ticket: "Billett",
    field_user: "Bruker",
    field_reason: "Årsak",
    field_created: "Opprettet",
    field_assigned_to: "Tildelt",
    field_escalated_by: "Eskalert av",
    field_invited_by: "Invitert av",
    field_queue_block: "Køsperring",
    button_rate_experience: "Vurder opplevelsen din",
    auto_closed_footer: "Hvis du fortsatt trenger hjelp, vennligst åpne en ny billett.",
    closed_status: "Lukket",
    yes: "Ja",
    no: "Nei",
    queue_joined_dm_description: "Du har blitt med i køen!\n\n**Posisjon:** {position}",
    queue_joined_channel_description: "Bruker ble med i køen",
    queue_ready_dm_description: "**Plassen din er klar!** Du er nå øverst i køen.",
    queue_ready_dm_join_hint: "Klikk på knappen nedenfor for å bli med i serveren.",
    queue_ready_channel_description: "Bruker nådde posisjon nr. 1 i køen",
    queue_position_dm_description: "Du er nå blant de **{milestone} første** i køen! Gjør deg klar til å bli med i serveren snart.",
    queue_kicked_dm_description: "Du har blitt **fjernet fra køen** av en moderator.",
    queue_kicked_reason: "**Årsak:** {reason}",
    application_submitted_dm_description: "Søknaden din for **{application_title}** er sendt inn!",
    application_submitted_channel_description: "En ny søknad er sendt inn for **{application_title}**",
    application_cosign_required_title: "Medsignering av søknad kreves",
    application_cosign_required_description: "En søknad for **{application_title}** venter på en andre godkjenning fra staff.",
    application_accepted_dm_title: "Søknad godkjent!",
    application_accepted_dm_description: "Gratulerer! Søknaden din for **{application_title}** har blitt **godkjent**!",
    application_accepted_channel_title: "Søknad godkjent",
    application_accepted_channel_description: "En søknad for **{application_title}** har blitt godkjent!",
    application_rejected_dm_title: "Søknad avvist",
    application_rejected_dm_description: "Dessverre har søknaden din for **{application_title}** blitt **avvist**.",
    application_rejected_channel_title: "Søknad avvist",
    application_rejected_channel_description: "En søknad for **{application_title}** har blitt avvist.",
    ticket_created_dm_title: "Billett opprettet",
    ticket_created_dm_description: "Støttebilletten din er opprettet!\n\n**{ticket_title}**",
    ticket_created_on_behalf_dm_description: "Et staffmedlem åpnet denne støttebilletten på dine vegne.\n\n**{ticket_title}**",
    ticket_created_channel_title: "Ny støttebillett",
    ticket_created_channel_description: "**{ticket_title}**",
    ticket_reply_dm_title: "Nytt svar på billetten din",
    ticket_reply_dm_description: "Du har fått et nytt svar på billett **#{ticket_id}: {ticket_title}**",
    ticket_reply_channel_title: "Billettsvar",
    ticket_reply_channel_description: "Nytt svar på billett **#{ticket_id}: {ticket_title}**",
    ticket_closed_dm_title: "Billett oppdatert",
    ticket_closed_dm_description: "Støttebilletten din **#{ticket_id}: {ticket_title}** er merket som **{status}**.",
    ticket_closed_channel_title: "Billett lukket",
    ticket_closed_channel_description: "Billett **#{ticket_id}: {ticket_title}** ble merket som **{status}**.",
    ticket_escalated_dm_title: "Billett eskalert",
    ticket_escalated_dm_description: "Billett **#{ticket_id}: {ticket_title}** er eskalert for gjennomgang av eier.",
    ticket_escalated_channel_title: "Billett eskalert",
    ticket_escalated_channel_description: "Billett **#{ticket_id}: {ticket_title}** ble eskalert for gjennomgang av eier.",
    ticket_overdue_title: "Billett forfalt",
    ticket_overdue_description: "Billett **#{ticket_id}: {ticket_title}** har overskredet SLA-svarfristen.",
    ticket_auto_closed_title: "Billett automatisk lukket",
    ticket_auto_closed_description: "Støttebilletten din er automatisk lukket på grunn av inaktivitet.\n\n**{ticket_title}**",
    ticket_invitation_title: "Billetinvitasjon",
    ticket_invitation_description: "Du er invitert til billett **#{ticket_id}: {ticket_title}**.",
    ticket_rating_prompt: "Vennligst vurder støtteopplevelsen din ved å bruke knappen nedenfor.",
  },
};

export default no;
