import type { TranslationKeys } from "./eng";

const tr: TranslationKeys = {
  // Common
  common: {
    save: "Kaydet",
    cancel: "İptal",
    delete: "Sil",
    edit: "Düzenle",
    back: "Geri",
    loading: "Yükleniyor...",
    confirm: "Onayla",
    yes: "Evet",
    no: "Hayır",
    enabled: "Etkin",
    disabled: "Devre dışı",
    configured: "Yapılandırıldı",
    not_configured: "Yapılandırılmadı",
    coming_soon: "Yakında",
    available: "Kullanılabilir",
    click_to_manage: "Yönetmek için tıkla",
    click_to_setup: "Kurmak için tıkla",
    click_to_customize: "Özelleştirmek için tıkla",
    required: "Gerekli",
    optional: "İsteğe bağlı",
    search: "Ara",
    no_results: "Sonuç bulunamadı",
    error: "Bir şeyler ters gitti",
    success: "Başarılı",
  },

  // Navigation / Sidebar
  nav: {
    dashboard: "Panel",
    queue: "Sıra",
    tickets: "Destek Talepleri",
    applications: "Başvurular",
    settings: "Ayarlar",
    logout: "Çıkış Yap",
    customer_dashboard: "Müşteri Paneli",
    view_queue_panel: "Sıra Panelini Görüntüle",
    view_queue_panel_hint: "Ayarların başvuruları, destek taleplerini ve sıra görünümünü nasıl etkilediğini kontrol etmek için sıra panelini önizle.",
  },

  // Auth
  auth: {
    login: "Discord ile Giriş Yap",
    logout: "Çıkış Yap",
    login_description: "Devam etmek için Discord hesabınla giriş yap",
  },

  // API errors
  errors: {
    unauthorized: "Kullanıcı doğrulanmadı",
    forbidden: "Yasak",
    insufficient_permissions: "Bu işlemi yapmak için iznin yok",
    bad_request: "Geçersiz istek",
    invalid_request: "Geçersiz istek",
    invalid_request_body: "Geçersiz istek gövdesi",
    internal_error: "Dahili sunucu hatası",
    not_found: "Kaynak bulunamadı",
    conflict: "Bu işlem mevcut durumla çakışıyor",
    owner_required: "Bu ayarı yalnızca müşteri güncelleyebilir",
    language_update_failed: "Dil ayarları kaydedilemedi",
    language_retrieval_failed: "Dil ayarları yüklenemedi",
    queue_disabled: "Sıra modülü şu anda devre dışı",
    queue_locked: "Sıra şu anda kilitli",
    queue_staff_only_locked: "Sıra şu anda yalnızca personele açık",
    discord_config_required: "Önce Discord entegrasyonunu yapılandır",
    customer_session_required: "Paneller arasında geçiş yapmak için müşteri oturumu gerekli.",
    customer_session_check_failed: "Müşteri oturumun doğrulanamadı.",
    steam_required: "Bu sıraya katılmadan önce Steam hesabı bağlaman gerekiyor",
    steam_banned: "Bu Steam hesabı bu sıraya katılmaktan yasaklanmış",
    discord_banned: "Bu Discord hesabı bu sıraya katılmaktan yasaklanmış",
    steam_recently_changed: "Steam hesabın yakın zamanda değiştirildi ve sıraya katılmadan önce bekleme süresini tamamlamalı",
    steam_unlink_disabled: "Bu sunucuda Steam bağlantısını kaldırma devre dışı",
  },

  // Steam identity
  steam_identity: {
    title: "Steam Kimliği",
    description: "Sunucuların sıra erişimini doğrulamasına ve alternatif hesaplarla ban atlatmayı caydırmasına yardımcı olmak için Steam'i bağla.",
    linked: "Steam bağlı",
    not_linked: "Bağlı Steam hesabı yok",
    link: "Steam'i Bağla",
    unlink: "Steam Bağlantısını Kaldır",
    recently_changed: "Yakın Zamanda Değişti",
    change_history: "Steam Değişiklik Geçmişi",
    required_title: "Steam hesabı gerekli",
    required_description: "Bu sunucu, sıraya katılmadan önce bağlı bir Steam hesabı gerektirir.",
  },

  // txAdmin bans
  txadmin_bans: {
    title: "txAdmin Ban Senkronizasyonu",
    description: "Steam ve Discord ban tanımlayıcılarını txAdmin playersDB.json dosyasından çek, sıra katılımlarında yenile ve txAdmin etkinliklerinden canlı ban/ban kaldırma bildirimlerini kabul et.",
    sync_now: "Şimdi Senkronize Et",
    sync_success: "Ban senkronizasyonu tamamlandı",
    sync_failed: "Banlar sunucu kaynağından senkronize edilemedi",
    active_bans: "Aktif Ban Tanımlayıcıları",
    last_manual_sync: "Son Manuel Senkronizasyon",
    last_server_push: "Son Sunucu Bildirimi",
    never: "Hiçbir zaman",
    resource_config: "Sunucu Kaynağı Senkronizasyon Yapılandırması",
  },

  // Customer dashboard
  customer: {
    welcome: "Tekrar hoş geldin, {name}!",
    subtitle: "FiveM sunucunun yapılandırmasını ve sıra ayarlarını yönet.",
    setup_progress: "Kurulum İlerlemesi",
    required_completed: "{completed} / {total} gerekli öğe tamamlandı",
    completed: "Tamamlandı",
    remaining: "Kalan",
    all_completed: "Tüm gerekli öğeler tamamlandı!",
    done: "Bitti",
    essential_setup: "Temel Kurulum",
    discord_configuration: "Discord Yapılandırması",
    features: "Özellikler",
    branding: "Markalaşma",
    fivem_title: "FiveM API Yapılandırması",
    fivem_desc_done: "FiveM sunucun yapılandırıldı ve sıra yönetimine hazır.",
    fivem_desc_pending: "Sıra yönetimini etkinleştirmek için FiveM API ayarlarını yapılandır.",
    discord_title: "Discord Kurulumu",
    discord_desc_done: "Discord botun yapılandırıldı ve sıra yönetimine hazır.",
    discord_desc_pending: "Sıra yönetimi için Discord bot token'ını ve sunucu ID'sini yapılandır.",
    tebex_title: "Tebex API Yapılandırması",
    tebex_desc_done: "Tebex API'n yapılandırıldı ve ödeme takibine hazır.",
    tebex_desc_pending: "Satın alma geçmişi takibini etkinleştirmek için Tebex API anahtarını yapılandır.",
    dashboard_roles_title: "Panel Rolleri Kurulumu",
    dashboard_roles_desc: "Panele erişebilen ve sıraya katılabilen Discord rollerini yapılandır.",
    dashboard_roles_locked: "Panel ve sıra erişim rollerini yapılandırmak için önce Discord kurulumunu tamamla.",
    queue_roles_title: "Sıra Oluşturucu",
    queue_roles_desc: "Öncelik rolleri, bypass slotları, erişim kuralları ve native kart davranışını yapılandır.",
    queue_roles_desc_done: "Sıra rollerin ve erişim akışın yapılandırıldı.",
    queue_roles_locked: "Sıra kurallarını ve erişimi yapılandırmak için önce Discord kurulumunu tamamla.",
    moderators_title: "Moderatörler",
    moderators_desc: "Sunucundaki destek taleplerini ve başvuruları yönetmeye yardımcı olacak moderatörler ekle.",
    moderators_desc_done: "Destek taleplerine ve başvurulara erişimi olan moderatörlerin var.",
    moderators_locked: "Moderatörleri yönetmek için önce Discord kurulumunu tamamla.",
    discord_required: "Önce Discord kurulumunu tamamla",
    module_settings_title: "Modül Ayarları",
    module_settings_desc: "Başvuru, destek talebi, bildirim ve personele yönelik modülleri etkinleştir veya devre dışı bırak.",
    application_builder_title: "Başvuru Oluşturucu",
    application_builder_desc: "Oyuncuların doldurabileceği özel sorularla form başvuruları oluştur ve yönet.",
    tickets_title: "Destek Talepleri",
    tickets_desc: "Destek talebi kategorilerini yönet ve oyuncular ile moderatörler için destek sistemini özelleştir.",
    notifications_title: "Discord Bildirimleri",
    notifications_desc: "Sıra, başvurular ve destek talepleri için Discord bildirimlerini yapılandır",
    queue_builder_title: "Sıra Oluşturucu",
    queue_builder_desc: "Gelişmiş kurallar, öncelikler ve otomasyon özellikleriyle sıra sistemini oluştur ve özelleştir.",
    language_title: "Dil",
    language_desc: "Oyuncuların göreceği arayüz dilini ayarla.",
    app_customization_title: "Uygulama Özelleştirme",
    app_customization_desc: "Tüm uygulamaya uygulanan ana renk gibi genel uygulama ayarlarını özelleştir.",
    dashboard_customization_title: "Panel Özelleştirme",
    dashboard_customization_desc: "Senin ve tüm oyuncuların/moderatörlerin göreceği panel gezinme çubuğu logosunu özelleştir.",
    home_page_title: "Ana Sayfa Özelleştirme",
    home_page_desc: "Oyuncular için ana sayfanın görünümünü, içeriğini ve hızlı bağlantılarını özelleştir.",
    login_customization_title: "Giriş Özelleştirme",
    login_customization_desc: "Giriş sayfanın görünümünü, markasını ve kimlik doğrulama akışını özelleştir.",
    custom_domain_title: "Özel Alan Adı",
    custom_domain_desc_done: "Özel alan adın yapılandırıldı ve kullanıma hazır.",
    custom_domain_desc_pending: "Ana sayfanda kendi alan adını kullanmak için özel alan adı yapılandır.",
  },

  // Language settings page
  language: {
    title: "Dil",
    description: "Oyuncuların göreceği arayüz dilini ayarla.",
    select_label: "Arayüz Dili",
    select_description: "Oyuncuların sıra, destek talepleri ve başvuruları kullanırken göreceği dili belirler.",
    select_language: "Dil Seç",
    select_language_description: "Oyuncuların sıra, destek talepleri ve başvuruları kullanırken göreceği dili seç.",
    customize_title: "Çeviri Geçersiz Kılmaları",
    customize_description: "Kurulumun tarafından kullanılan çeviri içeriğini düzenle. Anahtarları ve yer tutucuları olduğu gibi bırak.",
    download: "Çeviri Dosyasını İndir",
    reset: "Varsayılanlara Sıfırla",
    save_success: "Dil başarıyla kaydedildi",
    save_error: "Dil kaydedilemedi",
    invalid_json: "Çeviriler geçerli JSON olmalıdır",
    mode_label: "Dil Kaynağı",
    mode_preset: "Hazır",
    mode_custom: "Özel",
    preset_description: "Herkese açık dil deposu tarafından sürdürülen paket çeviri dosyalarından birini kullan.",
    custom_description: "Bu kurulum için aşağıdaki müşteriye özel çeviri JSON'unu kullan.",
    english: "İngilizce",
    spanish: "İspanyolca",
    norwegian: "Norveççe",
  },

  // Queue
  queue: {
    title: "Sıra",
    position: "Pozisyon",
    join: "Sıraya Katıl",
    leave: "Sıradan Ayrıl",
    players_in_queue: "Sırada {count} oyuncu var",
    your_position: "Sıradaki yerin: {position}",
    estimated_wait: "Tahmini bekleme: {time}",
    queue_closed: "Sıra kapalı",
    queue_open: "Sıra açık",
  },

  // Tickets
  tickets: {
    title: "Destek Talepleri",
    create: "Destek Talebi Oluştur",
    open: "Açık",
    closed: "Kapalı",
    no_tickets: "Henüz destek talebi yok",
    subject: "Konu",
    description: "Açıklama",
    status: "Durum",
    created_at: "Oluşturuldu",
    updated_at: "Son güncelleme",
    close_ticket: "Destek Talebini Kapat",
    ticket_closed: "Destek talebi kapatıldı",
    message_placeholder: "Mesajını yaz...",
    send: "Gönder",
    create_modal_title: "Yeni Destek Talebi Oluştur",
    create_success: "Destek talebi başarıyla oluşturuldu!",
    create_error: "Destek talebi oluşturulamadı. Lütfen tekrar dene.",
    related_title: "İlgili Destek Talepleri",
    related_count: "{count} bağlı destek talebi",
    related_search_label: "Destek Talebi ID'sine göre ara",
    related_link: "Bağla",
    related_linked: "İlgili destek talebi bağlandı",
    related_link_failed: "İlgili destek talebi bağlanamadı",
    related_removed: "İlgili destek talebi kaldırıldı",
    related_remove_failed: "İlgili destek talebi kaldırılamadı",
    related_loading: "Destek talebi yükleniyor...",
    related_none_found: "Bu ID için bağlanabilir destek talebi bulunamadı.",
    related_none_linked: "Bağlı ilgili destek talebi yok.",
    related_remove: "Kaldır",
    watcher_started: "Destek talebi izleniyor",
    watcher_stopped: "Destek talebi izleme durduruldu",
    watcher_dm_description: "Bu destek talebine biri yanıt verdiğinde DM al.",
  },

  // Applications
  applications: {
    title: "Başvurular",
    submit: "Başvuru Gönder",
    no_applications: "Mevcut başvuru yok",
    submitted: "Başvuru başarıyla gönderildi",
    already_submitted: "Bu başvuruyu zaten gönderdin",
    status: "Durum",
    pending: "Beklemede",
    approved: "Onaylandı",
    rejected: "Reddedildi",
    rejected_success: "Başvuru reddedildi",
    cosigned_success: "Başvuru ikinci onay aldı",
    no_internal_notes: "Henüz dahili not yok.",
  },

  // Discord notifications
  discord_notifications: {
    field_ticket_id: "Destek Talebi ID'si",
    field_priority: "Öncelik",
    field_status: "Durum",
    field_created_by: "Oluşturan",
    field_opened_for: "Adına açılan",
    field_category: "Kategori",
    field_description: "Açıklama",
    field_from: "Gönderen",
    field_reply: "Yanıt",
    field_ticket: "Destek Talebi",
    field_user: "Kullanıcı",
    field_reason: "Sebep",
    field_created: "Oluşturuldu",
    field_assigned_to: "Atanan",
    field_escalated_by: "Yükselten",
    field_invited_by: "Davet eden",
    field_queue_block: "Sıra Engeli",
    button_rate_experience: "Deneyimini değerlendir",
    auto_closed_footer: "Hâlâ yardıma ihtiyacın varsa lütfen yeni bir destek talebi aç.",
    closed_status: "Kapalı",
    yes: "Evet",
    no: "Hayır",
    queue_joined_dm_description: "Sıraya başarıyla katıldın!\n\n**Pozisyon:** {position}",
    queue_joined_channel_description: "Kullanıcı sıraya katıldı",
    queue_ready_dm_description: "**Sıran hazır!** Artık sıranın en başındasın.",
    queue_ready_dm_join_hint: "Sunucuya katılmak için aşağıdaki butona tıkla.",
    queue_ready_channel_description: "Kullanıcı sırada #1 pozisyonuna ulaştı",
    queue_position_dm_description: "Artık sırada **ilk {milestone}** içindesin! Yakında sunucuya katılmaya hazır ol.",
    queue_kicked_dm_description: "Bir moderatör tarafından **sıradan çıkarıldın**.",
    queue_kicked_reason: "**Sebep:** {reason}",
    application_submitted_dm_description: "**{application_title}** başvurun başarıyla gönderildi!",
    application_submitted_channel_description: "**{application_title}** için yeni bir başvuru gönderildi",
    application_cosign_required_title: "Başvuru İçin İkinci Onay Gerekli",
    application_cosign_required_description: "**{application_title}** için bir başvuru ikinci personel onayını bekliyor.",
    application_accepted_dm_title: "Başvuru Kabul Edildi!",
    application_accepted_dm_description: "Tebrikler! **{application_title}** başvurun **kabul edildi**!",
    application_accepted_channel_title: "Başvuru Kabul Edildi",
    application_accepted_channel_description: "**{application_title}** için bir başvuru kabul edildi!",
    application_rejected_dm_title: "Başvuru Reddedildi",
    application_rejected_dm_description: "Maalesef **{application_title}** başvurun **reddedildi**.",
    application_rejected_channel_title: "Başvuru Reddedildi",
    application_rejected_channel_description: "**{application_title}** için bir başvuru reddedildi.",
    ticket_created_dm_title: "Destek Talebi Oluşturuldu",
    ticket_created_dm_description: "Destek talebin başarıyla oluşturuldu!\n\n**{ticket_title}**",
    ticket_created_on_behalf_dm_description: "Bir personel üyesi senin adına bu destek talebini açtı.\n\n**{ticket_title}**",
    ticket_created_channel_title: "Yeni Destek Talebi",
    ticket_created_channel_description: "**{ticket_title}**",
    ticket_reply_dm_title: "Destek Talebine Yeni Yanıt",
    ticket_reply_dm_description: "**#{ticket_id}: {ticket_title}** destek talebinde yeni bir yanıtın var",
    ticket_reply_channel_title: "Destek Talebi Yanıtı",
    ticket_reply_channel_description: "**#{ticket_id}: {ticket_title}** destek talebinde yeni yanıt",
    ticket_closed_dm_title: "Destek Talebi Güncellendi",
    ticket_closed_dm_description: "**#{ticket_id}: {ticket_title}** destek talebin **{status}** olarak işaretlendi.",
    ticket_closed_channel_title: "Destek Talebi Kapatıldı",
    ticket_closed_channel_description: "**#{ticket_id}: {ticket_title}** destek talebi **{status}** olarak işaretlendi.",
    ticket_escalated_dm_title: "Destek Talebi Yükseltildi",
    ticket_escalated_dm_description: "**#{ticket_id}: {ticket_title}** destek talebi sahip incelemesi için yükseltildi.",
    ticket_escalated_channel_title: "Destek Talebi Yükseltildi",
    ticket_escalated_channel_description: "**#{ticket_id}: {ticket_title}** destek talebi sahip incelemesi için yükseltildi.",
    ticket_overdue_title: "Destek Talebi Gecikti",
    ticket_overdue_description: "**#{ticket_id}: {ticket_title}** destek talebi SLA yanıt süresini aştı.",
    ticket_auto_closed_title: "Destek Talebi Otomatik Kapatıldı",
    ticket_auto_closed_description: "Destek talebin hareketsizlik nedeniyle otomatik olarak kapatıldı.\n\n**{ticket_title}**",
    ticket_invitation_title: "Destek Talebi Daveti",
    ticket_invitation_description: "**#{ticket_id}: {ticket_title}** destek talebine davet edildin.",
    ticket_rating_prompt: "Lütfen aşağıdaki butonu kullanarak destek deneyimini değerlendir.",
  },
};

export default tr;
